import Head from "next/head";
import React from "react";
import { useRouter } from "next/router";
import BookingSelect from "~/components/BookingSelect";
import Features from "~/components/Features";
import Footer from "~/components/Footer";
import Navbar from "~/components/NavBar";
import PaymentFooter from "~/components/PaymentFooter";

const Booking = (props) => {
  return (
    <>
      <Head>
        <title>Car Parking | Booking</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <Navbar />
        <div className="h-screen">
          {/* <div className="mx-auto w-[800px] bg-slate-800 shadow-lg md:bg-opacity-70  "> */}
          {/* <MyDatePicker /> */}
          <BookingSelect />
          {/* </div> */}
        </div>
        <Features />
        <PaymentFooter />
        <Footer />
      </div>
      ;
    </>
  );
};

export default Booking;
