"use client";
import React, { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";

import { SignIn, SignInButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
// import type { RouterOutputs } from "~/utils/api";
import Image from "next/image";
import Navbar from "~/components/NavBar";
// import Hero from "~/assets/images/home.jpg";
import HeroImage from "~/assets/images/hero.jpg";
import Features from "~/components/Features";
import Footer from "~/components/Footer";
// import DateChecker from "~/components/DateChecker";
import BookingComponent from "~/components/BookingComponent";
const inter = Inter({
  subsets: ["latin-ext"],
});
const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Car Parking | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Navbar />
        <div className="">
          <Image
            src={HeroImage}
            width={500}
            height={200}
            alt="Hero Image"
            className=" w-[100%] bg-cover bg-left bg-no-repeat md:h-[90vh] md:bg-fixed"
          />

          <div className="transparent z-10 mx-auto w-[100%] rounded-xl bg-slate-300 bg-opacity-30 p-5 sm:right-[150px] sm:top-[100px] sm:w-[1200px] md:absolute md:right-[300px] md:top-[200px] md:w-[1200px]  md:bg-opacity-60">
            {/* <DateChecker /> */}
            <BookingComponent />
          </div>
        </div>
        <div>
          <Features />
        </div>
        {/* </div> */}
        {/* <PreBook />
        <HowTo /> */}

        {/* <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex justify-center border-b border-slate-400 p-4">
          {!user.isSignedIn && (
            <div className="flex justify-center">
            <SignInButton />{" "}
            </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
            </div>
            <div className="flex flex-col">
            {[data]?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
              ))}
              </div>
              </div>
            <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" /> */}

        {/* <div className="bg-hero"></div> */}
        {/* <Image src={Hero} alt="Home" className="mx-auto  md:w-full" /> */}

        {/* <Footer /> */}
      </main>
      <Footer />
    </>
  );
};

export default Home;
